//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MWCore.SMSMessagingAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MessagingSoap", Namespace="http://itbsms.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseSendingRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResult))]
    public partial class Messaging : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Http_AuthenticateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback Http_GetSmsStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSmsStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback Http_SendSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSToDistributionListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllDistributionListsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSToAdZoneLocationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAdZoneLocationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAdZoneMessageStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Queued_MessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_DLR_DataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Messaging() {
            this.Url = global::MWCore.Properties.Settings.Default.MWCore_SMSMessagingAPI_Messaging;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Http_AuthenticateUserCompletedEventHandler Http_AuthenticateUserCompleted;
        
        /// <remarks/>
        public event AuthenticateUserCompletedEventHandler AuthenticateUserCompleted;
        
        /// <remarks/>
        public event Http_GetSmsStatusCompletedEventHandler Http_GetSmsStatusCompleted;
        
        /// <remarks/>
        public event GetSmsStatusCompletedEventHandler GetSmsStatusCompleted;
        
        /// <remarks/>
        public event Http_SendSMSCompletedEventHandler Http_SendSMSCompleted;
        
        /// <remarks/>
        public event SendSMSCompletedEventHandler SendSMSCompleted;
        
        /// <remarks/>
        public event SendSMSToDistributionListCompletedEventHandler SendSMSToDistributionListCompleted;
        
        /// <remarks/>
        public event GetAllDistributionListsCompletedEventHandler GetAllDistributionListsCompleted;
        
        /// <remarks/>
        public event SendSMSToAdZoneLocationCompletedEventHandler SendSMSToAdZoneLocationCompleted;
        
        /// <remarks/>
        public event GetAdZoneLocationsCompletedEventHandler GetAdZoneLocationsCompleted;
        
        /// <remarks/>
        public event GetAdZoneMessageStatusCompletedEventHandler GetAdZoneMessageStatusCompleted;
        
        /// <remarks/>
        public event Get_Queued_MessagesCompletedEventHandler Get_Queued_MessagesCompleted;
        
        /// <remarks/>
        public event Get_DLR_DataCompletedEventHandler Get_DLR_DataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itbsms.com/Http_AuthenticateUser", RequestNamespace="http://itbsms.com/", ResponseNamespace="http://itbsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AuthenticationResult Http_AuthenticateUser(string username, string password, int customerId) {
            object[] results = this.Invoke("Http_AuthenticateUser", new object[] {
                        username,
                        password,
                        customerId});
            return ((AuthenticationResult)(results[0]));
        }
        
        /// <remarks/>
        public void Http_AuthenticateUserAsync(string username, string password, int customerId) {
            this.Http_AuthenticateUserAsync(username, password, customerId, null);
        }
        
        /// <remarks/>
        public void Http_AuthenticateUserAsync(string username, string password, int customerId, object userState) {
            if ((this.Http_AuthenticateUserOperationCompleted == null)) {
                this.Http_AuthenticateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHttp_AuthenticateUserOperationCompleted);
            }
            this.InvokeAsync("Http_AuthenticateUser", new object[] {
                        username,
                        password,
                        customerId}, this.Http_AuthenticateUserOperationCompleted, userState);
        }
        
        private void OnHttp_AuthenticateUserOperationCompleted(object arg) {
            if ((this.Http_AuthenticateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Http_AuthenticateUserCompleted(this, new Http_AuthenticateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itbsms.com/AuthenticateUser", RequestNamespace="http://itbsms.com/", ResponseNamespace="http://itbsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AuthenticationResult AuthenticateUser(SoapUser user) {
            object[] results = this.Invoke("AuthenticateUser", new object[] {
                        user});
            return ((AuthenticationResult)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(SoapUser user) {
            this.AuthenticateUserAsync(user, null);
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(SoapUser user, object userState) {
            if ((this.AuthenticateUserOperationCompleted == null)) {
                this.AuthenticateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserOperationCompleted);
            }
            this.InvokeAsync("AuthenticateUser", new object[] {
                        user}, this.AuthenticateUserOperationCompleted, userState);
        }
        
        private void OnAuthenticateUserOperationCompleted(object arg) {
            if ((this.AuthenticateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateUserCompleted(this, new AuthenticateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itbsms.com/Http_GetSmsStatus", RequestNamespace="http://itbsms.com/", ResponseNamespace="http://itbsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SMSStatusResult Http_GetSmsStatus(string username, string password, int customerId, string messageId, bool detailed) {
            object[] results = this.Invoke("Http_GetSmsStatus", new object[] {
                        username,
                        password,
                        customerId,
                        messageId,
                        detailed});
            return ((SMSStatusResult)(results[0]));
        }
        
        /// <remarks/>
        public void Http_GetSmsStatusAsync(string username, string password, int customerId, string messageId, bool detailed) {
            this.Http_GetSmsStatusAsync(username, password, customerId, messageId, detailed, null);
        }
        
        /// <remarks/>
        public void Http_GetSmsStatusAsync(string username, string password, int customerId, string messageId, bool detailed, object userState) {
            if ((this.Http_GetSmsStatusOperationCompleted == null)) {
                this.Http_GetSmsStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHttp_GetSmsStatusOperationCompleted);
            }
            this.InvokeAsync("Http_GetSmsStatus", new object[] {
                        username,
                        password,
                        customerId,
                        messageId,
                        detailed}, this.Http_GetSmsStatusOperationCompleted, userState);
        }
        
        private void OnHttp_GetSmsStatusOperationCompleted(object arg) {
            if ((this.Http_GetSmsStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Http_GetSmsStatusCompleted(this, new Http_GetSmsStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itbsms.com/GetSmsStatus", RequestNamespace="http://itbsms.com/", ResponseNamespace="http://itbsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SMSStatusResult GetSmsStatus(SoapUser user, System.Guid messageId, bool detailed) {
            object[] results = this.Invoke("GetSmsStatus", new object[] {
                        user,
                        messageId,
                        detailed});
            return ((SMSStatusResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetSmsStatusAsync(SoapUser user, System.Guid messageId, bool detailed) {
            this.GetSmsStatusAsync(user, messageId, detailed, null);
        }
        
        /// <remarks/>
        public void GetSmsStatusAsync(SoapUser user, System.Guid messageId, bool detailed, object userState) {
            if ((this.GetSmsStatusOperationCompleted == null)) {
                this.GetSmsStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSmsStatusOperationCompleted);
            }
            this.InvokeAsync("GetSmsStatus", new object[] {
                        user,
                        messageId,
                        detailed}, this.GetSmsStatusOperationCompleted, userState);
        }
        
        private void OnGetSmsStatusOperationCompleted(object arg) {
            if ((this.GetSmsStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSmsStatusCompleted(this, new GetSmsStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itbsms.com/Http_SendSMS", RequestNamespace="http://itbsms.com/", ResponseNamespace="http://itbsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendingSMSResult Http_SendSMS(string username, string password, int customerId, string senderText, string messageBody, string recipientNumbers, string defDate, bool isBlink, bool isFlash) {
            object[] results = this.Invoke("Http_SendSMS", new object[] {
                        username,
                        password,
                        customerId,
                        senderText,
                        messageBody,
                        recipientNumbers,
                        defDate,
                        isBlink,
                        isFlash});
            return ((SendingSMSResult)(results[0]));
        }
        
        /// <remarks/>
        public void Http_SendSMSAsync(string username, string password, int customerId, string senderText, string messageBody, string recipientNumbers, string defDate, bool isBlink, bool isFlash) {
            this.Http_SendSMSAsync(username, password, customerId, senderText, messageBody, recipientNumbers, defDate, isBlink, isFlash, null);
        }
        
        /// <remarks/>
        public void Http_SendSMSAsync(string username, string password, int customerId, string senderText, string messageBody, string recipientNumbers, string defDate, bool isBlink, bool isFlash, object userState) {
            if ((this.Http_SendSMSOperationCompleted == null)) {
                this.Http_SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHttp_SendSMSOperationCompleted);
            }
            this.InvokeAsync("Http_SendSMS", new object[] {
                        username,
                        password,
                        customerId,
                        senderText,
                        messageBody,
                        recipientNumbers,
                        defDate,
                        isBlink,
                        isFlash}, this.Http_SendSMSOperationCompleted, userState);
        }
        
        private void OnHttp_SendSMSOperationCompleted(object arg) {
            if ((this.Http_SendSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Http_SendSMSCompleted(this, new Http_SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itbsms.com/SendSMS", RequestNamespace="http://itbsms.com/", ResponseNamespace="http://itbsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendingSMSResult SendSMS(SendingSMSRequest sendingRequest) {
            object[] results = this.Invoke("SendSMS", new object[] {
                        sendingRequest});
            return ((SendingSMSResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSAsync(SendingSMSRequest sendingRequest) {
            this.SendSMSAsync(sendingRequest, null);
        }
        
        /// <remarks/>
        public void SendSMSAsync(SendingSMSRequest sendingRequest, object userState) {
            if ((this.SendSMSOperationCompleted == null)) {
                this.SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSOperationCompleted);
            }
            this.InvokeAsync("SendSMS", new object[] {
                        sendingRequest}, this.SendSMSOperationCompleted, userState);
        }
        
        private void OnSendSMSOperationCompleted(object arg) {
            if ((this.SendSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSCompleted(this, new SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itbsms.com/SendSMSToDistributionList", RequestNamespace="http://itbsms.com/", ResponseNamespace="http://itbsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendingDistributionListSMSResult SendSMSToDistributionList(SendingDistributionListSMSRequest sendingRequest) {
            object[] results = this.Invoke("SendSMSToDistributionList", new object[] {
                        sendingRequest});
            return ((SendingDistributionListSMSResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSToDistributionListAsync(SendingDistributionListSMSRequest sendingRequest) {
            this.SendSMSToDistributionListAsync(sendingRequest, null);
        }
        
        /// <remarks/>
        public void SendSMSToDistributionListAsync(SendingDistributionListSMSRequest sendingRequest, object userState) {
            if ((this.SendSMSToDistributionListOperationCompleted == null)) {
                this.SendSMSToDistributionListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSToDistributionListOperationCompleted);
            }
            this.InvokeAsync("SendSMSToDistributionList", new object[] {
                        sendingRequest}, this.SendSMSToDistributionListOperationCompleted, userState);
        }
        
        private void OnSendSMSToDistributionListOperationCompleted(object arg) {
            if ((this.SendSMSToDistributionListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSToDistributionListCompleted(this, new SendSMSToDistributionListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itbsms.com/GetAllDistributionLists", RequestNamespace="http://itbsms.com/", ResponseNamespace="http://itbsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DistributionListsResult GetAllDistributionLists(SoapUser user) {
            object[] results = this.Invoke("GetAllDistributionLists", new object[] {
                        user});
            return ((DistributionListsResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllDistributionListsAsync(SoapUser user) {
            this.GetAllDistributionListsAsync(user, null);
        }
        
        /// <remarks/>
        public void GetAllDistributionListsAsync(SoapUser user, object userState) {
            if ((this.GetAllDistributionListsOperationCompleted == null)) {
                this.GetAllDistributionListsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllDistributionListsOperationCompleted);
            }
            this.InvokeAsync("GetAllDistributionLists", new object[] {
                        user}, this.GetAllDistributionListsOperationCompleted, userState);
        }
        
        private void OnGetAllDistributionListsOperationCompleted(object arg) {
            if ((this.GetAllDistributionListsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllDistributionListsCompleted(this, new GetAllDistributionListsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itbsms.com/SendSMSToAdZoneLocation", RequestNamespace="http://itbsms.com/", ResponseNamespace="http://itbsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendingDistributionListSMSResult SendSMSToAdZoneLocation(SendingAdZoneSMSRequest sendingRequest) {
            object[] results = this.Invoke("SendSMSToAdZoneLocation", new object[] {
                        sendingRequest});
            return ((SendingDistributionListSMSResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSToAdZoneLocationAsync(SendingAdZoneSMSRequest sendingRequest) {
            this.SendSMSToAdZoneLocationAsync(sendingRequest, null);
        }
        
        /// <remarks/>
        public void SendSMSToAdZoneLocationAsync(SendingAdZoneSMSRequest sendingRequest, object userState) {
            if ((this.SendSMSToAdZoneLocationOperationCompleted == null)) {
                this.SendSMSToAdZoneLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSToAdZoneLocationOperationCompleted);
            }
            this.InvokeAsync("SendSMSToAdZoneLocation", new object[] {
                        sendingRequest}, this.SendSMSToAdZoneLocationOperationCompleted, userState);
        }
        
        private void OnSendSMSToAdZoneLocationOperationCompleted(object arg) {
            if ((this.SendSMSToAdZoneLocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSToAdZoneLocationCompleted(this, new SendSMSToAdZoneLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itbsms.com/GetAdZoneLocations", RequestNamespace="http://itbsms.com/", ResponseNamespace="http://itbsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DistributionListsResult GetAdZoneLocations(SoapUser user) {
            object[] results = this.Invoke("GetAdZoneLocations", new object[] {
                        user});
            return ((DistributionListsResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetAdZoneLocationsAsync(SoapUser user) {
            this.GetAdZoneLocationsAsync(user, null);
        }
        
        /// <remarks/>
        public void GetAdZoneLocationsAsync(SoapUser user, object userState) {
            if ((this.GetAdZoneLocationsOperationCompleted == null)) {
                this.GetAdZoneLocationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdZoneLocationsOperationCompleted);
            }
            this.InvokeAsync("GetAdZoneLocations", new object[] {
                        user}, this.GetAdZoneLocationsOperationCompleted, userState);
        }
        
        private void OnGetAdZoneLocationsOperationCompleted(object arg) {
            if ((this.GetAdZoneLocationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdZoneLocationsCompleted(this, new GetAdZoneLocationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itbsms.com/GetAdZoneMessageStatus", RequestNamespace="http://itbsms.com/", ResponseNamespace="http://itbsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AdZoneMessageStatusResult GetAdZoneMessageStatus(SoapUser user, System.Guid messageId) {
            object[] results = this.Invoke("GetAdZoneMessageStatus", new object[] {
                        user,
                        messageId});
            return ((AdZoneMessageStatusResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetAdZoneMessageStatusAsync(SoapUser user, System.Guid messageId) {
            this.GetAdZoneMessageStatusAsync(user, messageId, null);
        }
        
        /// <remarks/>
        public void GetAdZoneMessageStatusAsync(SoapUser user, System.Guid messageId, object userState) {
            if ((this.GetAdZoneMessageStatusOperationCompleted == null)) {
                this.GetAdZoneMessageStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdZoneMessageStatusOperationCompleted);
            }
            this.InvokeAsync("GetAdZoneMessageStatus", new object[] {
                        user,
                        messageId}, this.GetAdZoneMessageStatusOperationCompleted, userState);
        }
        
        private void OnGetAdZoneMessageStatusOperationCompleted(object arg) {
            if ((this.GetAdZoneMessageStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdZoneMessageStatusCompleted(this, new GetAdZoneMessageStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itbsms.com/Get_Queued_Messages", RequestNamespace="http://itbsms.com/", ResponseNamespace="http://itbsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Queued_Messages_Result Get_Queued_Messages(string username, string password, int customerId) {
            object[] results = this.Invoke("Get_Queued_Messages", new object[] {
                        username,
                        password,
                        customerId});
            return ((Queued_Messages_Result)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Queued_MessagesAsync(string username, string password, int customerId) {
            this.Get_Queued_MessagesAsync(username, password, customerId, null);
        }
        
        /// <remarks/>
        public void Get_Queued_MessagesAsync(string username, string password, int customerId, object userState) {
            if ((this.Get_Queued_MessagesOperationCompleted == null)) {
                this.Get_Queued_MessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Queued_MessagesOperationCompleted);
            }
            this.InvokeAsync("Get_Queued_Messages", new object[] {
                        username,
                        password,
                        customerId}, this.Get_Queued_MessagesOperationCompleted, userState);
        }
        
        private void OnGet_Queued_MessagesOperationCompleted(object arg) {
            if ((this.Get_Queued_MessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Queued_MessagesCompleted(this, new Get_Queued_MessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itbsms.com/Get_DLR_Data", RequestNamespace="http://itbsms.com/", ResponseNamespace="http://itbsms.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeliveryReport_Result Get_DLR_Data(string username, string password, int customerId, string MessageGuid) {
            object[] results = this.Invoke("Get_DLR_Data", new object[] {
                        username,
                        password,
                        customerId,
                        MessageGuid});
            return ((DeliveryReport_Result)(results[0]));
        }
        
        /// <remarks/>
        public void Get_DLR_DataAsync(string username, string password, int customerId, string MessageGuid) {
            this.Get_DLR_DataAsync(username, password, customerId, MessageGuid, null);
        }
        
        /// <remarks/>
        public void Get_DLR_DataAsync(string username, string password, int customerId, string MessageGuid, object userState) {
            if ((this.Get_DLR_DataOperationCompleted == null)) {
                this.Get_DLR_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_DLR_DataOperationCompleted);
            }
            this.InvokeAsync("Get_DLR_Data", new object[] {
                        username,
                        password,
                        customerId,
                        MessageGuid}, this.Get_DLR_DataOperationCompleted, userState);
        }
        
        private void OnGet_DLR_DataOperationCompleted(object arg) {
            if ((this.Get_DLR_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_DLR_DataCompleted(this, new Get_DLR_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class AuthenticationResult : BaseResult {
        
        private int customerIdField;
        
        private decimal netPointsField;
        
        private System.DateTime balanceExpirationDateField;
        
        private string[] sendersField;
        
        /// <remarks/>
        public int customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal NetPoints {
            get {
                return this.netPointsField;
            }
            set {
                this.netPointsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime BalanceExpirationDate {
            get {
                return this.balanceExpirationDateField;
            }
            set {
                this.balanceExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string[] Senders {
            get {
                return this.sendersField;
            }
            set {
                this.sendersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeliveryReport_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Queued_Messages_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdZoneMessageStatusResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DistributionListsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseSendingResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingDistributionListSMSResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingSMSResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMSStatusResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticationResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class BaseResult {
        
        private string messageField;
        
        private bool resultField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingAdZoneSMSRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingDistributionListSMSRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingSMSRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public abstract partial class BaseSendingRequest {
        
        private SoapUser userField;
        
        private string senderTextField;
        
        private string messageBodyField;
        
        private System.Nullable<System.DateTime> defDateField;
        
        /// <remarks/>
        public SoapUser User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string SenderText {
            get {
                return this.senderTextField;
            }
            set {
                this.senderTextField = value;
            }
        }
        
        /// <remarks/>
        public string MessageBody {
            get {
                return this.messageBodyField;
            }
            set {
                this.messageBodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DefDate {
            get {
                return this.defDateField;
            }
            set {
                this.defDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SoapUser {
        
        private string usernameField;
        
        private string passwordField;
        
        private int customerIdField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SendingAdZoneSMSRequest : BaseSendingRequest {
        
        private System.Guid distributionListGuidField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private DayOfWeek[] sendingDaysField;
        
        private byte[] sendingHoursField;
        
        private int recipientsCountField;
        
        /// <remarks/>
        public System.Guid DistributionListGuid {
            get {
                return this.distributionListGuidField;
            }
            set {
                this.distributionListGuidField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public DayOfWeek[] SendingDays {
            get {
                return this.sendingDaysField;
            }
            set {
                this.sendingDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SendingHours {
            get {
                return this.sendingHoursField;
            }
            set {
                this.sendingHoursField = value;
            }
        }
        
        /// <remarks/>
        public int RecipientsCount {
            get {
                return this.recipientsCountField;
            }
            set {
                this.recipientsCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public enum DayOfWeek {
        
        /// <remarks/>
        Sunday,
        
        /// <remarks/>
        Monday,
        
        /// <remarks/>
        Tuesday,
        
        /// <remarks/>
        Wednesday,
        
        /// <remarks/>
        Thursday,
        
        /// <remarks/>
        Friday,
        
        /// <remarks/>
        Saturday,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SendingDistributionListSMSRequest : BaseSendingRequest {
        
        private System.Guid distributionListGuidField;
        
        private bool sendToAllTheDistributionListNumbersField;
        
        private int countField;
        
        private int offsetField;
        
        /// <remarks/>
        public System.Guid DistributionListGuid {
            get {
                return this.distributionListGuidField;
            }
            set {
                this.distributionListGuidField = value;
            }
        }
        
        /// <remarks/>
        public bool SendToAllTheDistributionListNumbers {
            get {
                return this.sendToAllTheDistributionListNumbersField;
            }
            set {
                this.sendToAllTheDistributionListNumbersField = value;
            }
        }
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public int Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SendingSMSRequest : BaseSendingRequest {
        
        private bool isBlinkField;
        
        private bool isFlashField;
        
        private string recipientNumbersField;
        
        /// <remarks/>
        public bool IsBlink {
            get {
                return this.isBlinkField;
            }
            set {
                this.isBlinkField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFlash {
            get {
                return this.isFlashField;
            }
            set {
                this.isFlashField = value;
            }
        }
        
        /// <remarks/>
        public string RecipientNumbers {
            get {
                return this.recipientNumbersField;
            }
            set {
                this.recipientNumbersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class Recipient {
        
        private string idField;
        
        private string numberField;
        
        private string networkField;
        
        private string referenceField;
        
        private string statusField;
        
        private string reportTimeField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Network {
            get {
                return this.networkField;
            }
            set {
                this.networkField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string ReportTime {
            get {
                return this.reportTimeField;
            }
            set {
                this.reportTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class AdZoneMsgStatus {
        
        private string campaignNameField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private AdZoneMsgtate statusField;
        
        private AdZoneMsgCompletionType completionTypeField;
        
        private System.DateTime completionTimeField;
        
        private int partsPerMessageField;
        
        private int totalRecipientsLimitField;
        
        private int totalMessagePartsLimitField;
        
        private int totalBillableRecipientsCountField;
        
        private int totalBillableMessagePartsField;
        
        private System.Guid messageGuidField;
        
        private int sentProviderMessageIdField;
        
        private System.DateTime createdOnUtcField;
        
        /// <remarks/>
        public string CampaignName {
            get {
                return this.campaignNameField;
            }
            set {
                this.campaignNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public AdZoneMsgtate Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public AdZoneMsgCompletionType CompletionType {
            get {
                return this.completionTypeField;
            }
            set {
                this.completionTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CompletionTime {
            get {
                return this.completionTimeField;
            }
            set {
                this.completionTimeField = value;
            }
        }
        
        /// <remarks/>
        public int PartsPerMessage {
            get {
                return this.partsPerMessageField;
            }
            set {
                this.partsPerMessageField = value;
            }
        }
        
        /// <remarks/>
        public int TotalRecipientsLimit {
            get {
                return this.totalRecipientsLimitField;
            }
            set {
                this.totalRecipientsLimitField = value;
            }
        }
        
        /// <remarks/>
        public int TotalMessagePartsLimit {
            get {
                return this.totalMessagePartsLimitField;
            }
            set {
                this.totalMessagePartsLimitField = value;
            }
        }
        
        /// <remarks/>
        public int TotalBillableRecipientsCount {
            get {
                return this.totalBillableRecipientsCountField;
            }
            set {
                this.totalBillableRecipientsCountField = value;
            }
        }
        
        /// <remarks/>
        public int TotalBillableMessageParts {
            get {
                return this.totalBillableMessagePartsField;
            }
            set {
                this.totalBillableMessagePartsField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid MessageGuid {
            get {
                return this.messageGuidField;
            }
            set {
                this.messageGuidField = value;
            }
        }
        
        /// <remarks/>
        public int SentProviderMessageId {
            get {
                return this.sentProviderMessageIdField;
            }
            set {
                this.sentProviderMessageIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedOnUtc {
            get {
                return this.createdOnUtcField;
            }
            set {
                this.createdOnUtcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public enum AdZoneMsgtate {
        
        /// <remarks/>
        Preprocessing,
        
        /// <remarks/>
        QueuedForCreation,
        
        /// <remarks/>
        CreatedButNotInitiated,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Running,
        
        /// <remarks/>
        Paused,
        
        /// <remarks/>
        Finalizing,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        CompletedAndBilled,
        
        /// <remarks/>
        Deleted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public enum AdZoneMsgCompletionType {
        
        /// <remarks/>
        NotYetCompleted,
        
        /// <remarks/>
        TargetMessagePartsLimitReached,
        
        /// <remarks/>
        EndDateReached,
        
        /// <remarks/>
        StoppedByUser,
        
        /// <remarks/>
        StoppedByAdmin,
        
        /// <remarks/>
        TerminatedByAdmin,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class DistributionListItem {
        
        private string nameField;
        
        private System.Guid guidField;
        
        private int totalCountField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        public int TotalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SMSNumbers {
        
        private string[] sentNumbersField;
        
        private string[] queuedNumbersField;
        
        private string[] rejectedNumbersField;
        
        /// <remarks/>
        public string[] SentNumbers {
            get {
                return this.sentNumbersField;
            }
            set {
                this.sentNumbersField = value;
            }
        }
        
        /// <remarks/>
        public string[] QueuedNumbers {
            get {
                return this.queuedNumbersField;
            }
            set {
                this.queuedNumbersField = value;
            }
        }
        
        /// <remarks/>
        public string[] RejectedNumbers {
            get {
                return this.rejectedNumbersField;
            }
            set {
                this.rejectedNumbersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SMSCounters {
        
        private int sentCountField;
        
        private int queuedCountField;
        
        private int rejectedCountField;
        
        /// <remarks/>
        public int SentCount {
            get {
                return this.sentCountField;
            }
            set {
                this.sentCountField = value;
            }
        }
        
        /// <remarks/>
        public int QueuedCount {
            get {
                return this.queuedCountField;
            }
            set {
                this.queuedCountField = value;
            }
        }
        
        /// <remarks/>
        public int RejectedCount {
            get {
                return this.rejectedCountField;
            }
            set {
                this.rejectedCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class DeliveryReport_Result : BaseResult {
        
        private int recipientsCountField;
        
        private Recipient[] detailsField;
        
        /// <remarks/>
        public int RecipientsCount {
            get {
                return this.recipientsCountField;
            }
            set {
                this.recipientsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Recipient[] Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class Queued_Messages_Result : BaseResult {
        
        private int queuedCountField;
        
        private string[] messagesIdsField;
        
        /// <remarks/>
        public int QueuedCount {
            get {
                return this.queuedCountField;
            }
            set {
                this.queuedCountField = value;
            }
        }
        
        /// <remarks/>
        public string[] MessagesIds {
            get {
                return this.messagesIdsField;
            }
            set {
                this.messagesIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class AdZoneMessageStatusResult : BaseResult {
        
        private AdZoneMsgStatus adZoneMsgStatusField;
        
        /// <remarks/>
        public AdZoneMsgStatus AdZoneMsgStatus {
            get {
                return this.adZoneMsgStatusField;
            }
            set {
                this.adZoneMsgStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class DistributionListsResult : BaseResult {
        
        private DistributionListItem[] distributionListsField;
        
        /// <remarks/>
        public DistributionListItem[] DistributionLists {
            get {
                return this.distributionListsField;
            }
            set {
                this.distributionListsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingDistributionListSMSResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendingSMSResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class BaseSendingResult : BaseResult {
        
        private decimal netPointsField;
        
        private System.Guid messageIdField;
        
        /// <remarks/>
        public decimal NetPoints {
            get {
                return this.netPointsField;
            }
            set {
                this.netPointsField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SendingDistributionListSMSResult : BaseSendingResult {
        
        private string distributionListNameField;
        
        private System.Guid distributionListGuidField;
        
        /// <remarks/>
        public string DistributionListName {
            get {
                return this.distributionListNameField;
            }
            set {
                this.distributionListNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid DistributionListGuid {
            get {
                return this.distributionListGuidField;
            }
            set {
                this.distributionListGuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SendingSMSResult : BaseSendingResult {
        
        private string[] rejectedNumbersField;
        
        /// <remarks/>
        public string[] RejectedNumbers {
            get {
                return this.rejectedNumbersField;
            }
            set {
                this.rejectedNumbersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itbsms.com/")]
    public partial class SMSStatusResult : BaseResult {
        
        private decimal netPointsField;
        
        private SMSCounters countersField;
        
        private SMSNumbers numbersField;
        
        /// <remarks/>
        public decimal NetPoints {
            get {
                return this.netPointsField;
            }
            set {
                this.netPointsField = value;
            }
        }
        
        /// <remarks/>
        public SMSCounters Counters {
            get {
                return this.countersField;
            }
            set {
                this.countersField = value;
            }
        }
        
        /// <remarks/>
        public SMSNumbers Numbers {
            get {
                return this.numbersField;
            }
            set {
                this.numbersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Http_AuthenticateUserCompletedEventHandler(object sender, Http_AuthenticateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Http_AuthenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Http_AuthenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AuthenticateUserCompletedEventHandler(object sender, AuthenticateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthenticationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthenticationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Http_GetSmsStatusCompletedEventHandler(object sender, Http_GetSmsStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Http_GetSmsStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Http_GetSmsStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SMSStatusResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SMSStatusResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetSmsStatusCompletedEventHandler(object sender, GetSmsStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSmsStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSmsStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SMSStatusResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SMSStatusResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Http_SendSMSCompletedEventHandler(object sender, Http_SendSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Http_SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Http_SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendingSMSResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendingSMSResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendSMSCompletedEventHandler(object sender, SendSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendingSMSResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendingSMSResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendSMSToDistributionListCompletedEventHandler(object sender, SendSMSToDistributionListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSToDistributionListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSToDistributionListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendingDistributionListSMSResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendingDistributionListSMSResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAllDistributionListsCompletedEventHandler(object sender, GetAllDistributionListsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllDistributionListsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllDistributionListsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DistributionListsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DistributionListsResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendSMSToAdZoneLocationCompletedEventHandler(object sender, SendSMSToAdZoneLocationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSToAdZoneLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSToAdZoneLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendingDistributionListSMSResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendingDistributionListSMSResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAdZoneLocationsCompletedEventHandler(object sender, GetAdZoneLocationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdZoneLocationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAdZoneLocationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DistributionListsResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DistributionListsResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAdZoneMessageStatusCompletedEventHandler(object sender, GetAdZoneMessageStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdZoneMessageStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAdZoneMessageStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AdZoneMessageStatusResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AdZoneMessageStatusResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Get_Queued_MessagesCompletedEventHandler(object sender, Get_Queued_MessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Queued_MessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Queued_MessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Queued_Messages_Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Queued_Messages_Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Get_DLR_DataCompletedEventHandler(object sender, Get_DLR_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_DLR_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_DLR_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeliveryReport_Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeliveryReport_Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591